package com.canzs.lhjz.pojo.entity;

// Generated 2014-9-21 20:27:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test", catalog = "lhjz")
public class Test implements java.io.Serializable {

	private Integer id;
	private String name;
	private Double age;

	public Test() {
	}

	public Test(Integer id) {
		this.id = id;
	}

	public Test(Integer id, String name, Double age) {
		this.id = id;
		this.name = name;
		this.age = age;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "age", precision = 22, scale = 0)
	public Double getAge() {
		return this.age;
	}

	public void setAge(Double age) {
		this.age = age;
	}

}
